source :rubygems

gem "sinatra", "~>1.3.1"
gem "rutema", "~>1.2.4"
gem "sqlite3","~>1.3.4"
gem "hoe",'~>2.12.2'
gem "ruport", "~>1.6.3"
gem "acts_as_reportable","~>1.1.1", :require=>"ruport/acts_as_reportable"
gem "rdoc","~>3.11"