#  Copyright (c) 2008 Vassilis Rizopoulos. All rights reserved.
# -*- ruby -*-
$:.unshift File.join(File.dirname(__FILE__),"lib")
require 'rubygems'
require 'rutema_web/main'
require 'hoe'

Hoe.spec('rutema_web') do |p|
  p.version=RutemaWeb::Version::STRING
  p.rubyforge_name = 'patir'
  p.author = "Vassilis Rizopoulos"
  p.email = "riva@braveworld.net"
  p.summary = 'rutema_web is the web frontend for rutema'
  p.description = p.paragraphs_of('README.txt', 1..5).join("\n\n")
  p.url = "http://patir.rubyforge.org/rutema"
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.extra_deps<<['rutema',"~>1.2.4"]
  p.extra_deps<<['sinatra','~>1.3.1']
  p.extra_deps<<["ruport", "~>1.6.3"]
  p.extra_deps<<["acts_as_reportable","~>1.1.1"]
  p.spec_extras={:executables=>["rutema_web"],:default_executable=>"rutema_web"}
end
