#  Copyright (c) 2008 Vassilis Rizopoulos. All rights reserved.
# -*- ruby -*-
$:.unshift File.join(File.dirname(__FILE__),"lib")
require 'rutema_web/main'
require 'rubygems'
require 'hoe'

Hoe.spec('rutema_web') do |p|
  p.version=RutemaWeb::Version::STRING
  p.rubyforge_name = 'patir'
  p.author = "Vassilis Rizopoulos"
  p.email = "riva@braveworld.net"
  p.summary = 'rutema_web is the web frontend for rutema'
  p.description = p.paragraphs_of('README.txt', 1..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.extra_deps<<['rutema',"1.0.7"]
  p.extra_deps<<['sinatra','0.9.4']
  p.extra_deps<<['ruport','>=1.6.1']
  p.spec_extras={:executables=>["rutema_web"],
    :default_executable=>"rutema_web"}
end
