require 'rubygems'
gem 'activerecord','=2.3.2'
require 'active_record'
gem 'patir','>=0.6.0'
require 'patir/configuration'
require 'patir/command'
require 'patir/base'

require 'ruport/acts_as_reportable'
require 'mailfactory'
require 'highline'