#  Copyright (c) 2007 Vassilis Rizopoulos. All rights reserved.
# -*- ruby -*-
$:.unshift File.join(File.dirname(__FILE__),"lib")
require 'rutema/elements/general'
require 'rubygems'
require 'hoe'

Hoe.new('rutema_elements', "#{Rutema::Elements::Version::STRING}") do |p|
  p.rubyforge_name = 'patir'
  p.author = "Vassilis Rizopoulos"
  p.email = "riva@braveworld.net"
  p.summary = 'rutema elements provides modules that can be used with custom parsers to add elements to rutema specifications'
  p.description = p.paragraphs_of('README.txt', 1..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.extra_deps<<['rutema',">=1.0.0"]
  p.extra_deps<<['patir',">=0.6.1"]
end
# vim: syntax=Ruby