source :rubygems

gem "activerecord", "~>3.0.9",:require=>"active_record"
gem "patir", "~>0.7.0"
gem "ruport", "~>1.6.3"
gem "acts_as_reportable","~>1.1.1", :require=>"ruport/acts_as_reportable"
gem "highline","~>1.6.2"
gem "mailfactory","~>1.4.0"
gem "couchrest_model","~>1.1.2"
gem "mocha","~>0.9.12"
gem "sqlite3","~>1.3.4"